/// `__manifest__.py` template builder.
library odoo_model_generator.templates.manifest_template;

import '../core/model_builder.dart';
import '../utils/naming_conventions.dart';
import '../utils/string_utils.dart';

// ─────────────────────────────────────────────────────────────────────────────
//  ManifestTemplate
// ─────────────────────────────────────────────────────────────────────────────

/// Builds the complete `__manifest__.py` file content.
abstract final class ManifestTemplate {
  ManifestTemplate._();

  /// Renders the manifest dictionary.
  static String render(OdooModel model, GeneratorConfig config) {
    final label = NamingConventions.toLabel(model.modelName);
    final summary = StringUtils.escapeSingle(
      model.docstring ?? 'Custom module for ${label}',
    );

    // Merge all dependencies
    final deps = <String>{'base', ...model.dependencies, ...config.extraDependencies}
        .toList();

    // Data files
    final dataFiles = <String>[
      'security/ir.model.access.csv',
      'views/${NamingConventions.viewFileName(model.modelName)}',
    ];
    if (config.generateDemoStub) {
      dataFiles.add('data/demo.xml');
    }

    final buf = StringBuffer();
    buf.writeln('# -*- coding: utf-8 -*-');
    buf.writeln('# Generated by odoo_model_generator v2.0.0');
    buf.writeln('{');
    buf.writeln("    'name': '$label',");
    buf.writeln("    'version': '${config.version}',");
    buf.writeln("    'category': '${config.category}',");
    buf.writeln("    'summary': '$summary',");
    buf.writeln("    'author': '${config.author}',");
    buf.writeln("    'website': '${config.website}',");
    buf.writeln("    'license': '${config.license}',");
    buf.writeln("    'installable': True,");
    buf.writeln(
        "    'application': ${config.isApplication ? 'True' : 'False'},");
    buf.writeln("    'auto_install': False,");
    buf.writeln("    'depends': [");
    for (final dep in deps) {
      buf.writeln("        '$dep',");
    }
    buf.writeln("    ],");
    buf.writeln("    'data': [");
    for (final f in dataFiles) {
      buf.writeln("        '$f',");
    }
    buf.writeln("    ],");
    buf.writeln("    'demo': [],");
    buf.writeln("    'post_init_hook': None,");
    buf.writeln("    'uninstall_hook': None,");
    buf.writeln('}');

    return buf.toString();
  }
}
