/// Python model file template helpers.
///
/// These are pure string-building functions. They do NOT depend on any I/O.
library odoo_model_generator.templates.model_template;

import '../core/model_builder.dart';
import '../core/field_types.dart';
import '../utils/naming_conventions.dart';
import '../utils/string_utils.dart';

// ─────────────────────────────────────────────────────────────────────────────
//  ModelTemplate
// ─────────────────────────────────────────────────────────────────────────────

/// Builds the complete `models/<name>.py` file content.
abstract final class ModelTemplate {
  ModelTemplate._();

  // ── imports ───────────────────────────────────────────────────────────────

  static String imports(OdooModel model) {
    final buf = StringBuffer();
    buf.writeln('# -*- coding: utf-8 -*-');
    buf.writeln('# This file was generated by odoo_model_generator v2.0.0');
    buf.writeln('# DO NOT edit manually unless you know what you are doing.');
    buf.writeln();
    buf.writeln('from odoo import models, fields, api');
    buf.writeln('from odoo.exceptions import ValidationError, UserError');

    // Mail / activity mixins need extra imports
    if (model.inherits.any((i) => i.startsWith('mail.'))) {
      buf.writeln('from odoo.addons.mail.mixins.mail_thread import MailThread');
    }

    buf.writeln();
    return buf.toString();
  }

  // ── class header ──────────────────────────────────────────────────────────

  static String classHeader(OdooModel model) {
    final className = NamingConventions.toPythonClass(model.modelName);
    final description = StringUtils.escapeSingle(
      model.docstring ?? NamingConventions.toLabel(model.modelName),
    );

    final buf = StringBuffer();

    // Class declaration
    buf.writeln('class $className(models.Model):');

    // _name
    buf.writeln("    _name = '${model.modelName}'");

    // _description
    buf.writeln("    _description = '$description'");

    // _rec_name
    buf.writeln("    _rec_name = '${model.stringField}'");

    // _order
    if (model.order != null) {
      buf.writeln("    _order = '${model.order}'");
    }

    // _inherit
    if (model.inherits.isNotEmpty) {
      if (model.inherits.length == 1 &&
          model.inheritMode == InheritMode.mixin) {
        buf.writeln("    _inherit = ['${model.inherits.first}']");
      } else {
        final joined =
            model.inherits.map((i) => "'$i'").join(', ');
        buf.writeln("    _inherit = [$joined]");
      }
    }

    // _sql_constraints
    if (model.sqlConstraints.isNotEmpty) {
      buf.writeln();
      buf.writeln('    _sql_constraints = [');
      for (final (id, expr, msg) in model.sqlConstraints) {
        buf.writeln(
          "        ('$id', '$expr', '${StringUtils.escapeSingle(msg)}'),",
        );
      }
      buf.writeln('    ]');
    }

    buf.writeln();
    return buf.toString();
  }

  // ── field declarations ────────────────────────────────────────────────────

  static String fieldDeclarations(OdooModel model) {
    final buf = StringBuffer();

    // Sequence field (optional)
    if (model.createSequence) {
      buf.writeln("    sequence = fields.Integer("
          "string='Sequence', default=10)");
    }

    // User-declared fields
    for (final f in model.fields) {
      buf.writeln('    ${f.name} = ${f.toPython()}');
    }

    // Shadow timestamp fields (readonly, already managed by Odoo ORM)
    if (model.createTimestamp) {
      buf.writeln();
      buf.writeln('    # Auto-managed ORM timestamps (read-only shadows)');
      buf.writeln(
          "    create_date_display = fields.Datetime(string='Created On', "
          "related='create_date', readonly=True, store=False)");
      buf.writeln(
          "    write_date_display = fields.Datetime(string='Last Modified On', "
          "related='write_date', readonly=True, store=False)");
    }

    buf.writeln();
    return buf.toString();
  }

  // ── compute methods ───────────────────────────────────────────────────────

  static String computeMethods(OdooModel model) {
    if (model.computes.isEmpty) return '';

    final buf = StringBuffer();
    buf.writeln('    # ── Compute methods ──────────────────────────────────');
    buf.writeln();

    for (final cd in model.computes) {
      final deps = cd.dependsOn.map((d) => "'$d'").join(', ');
      buf.writeln('    @api.depends($deps)');
      buf.writeln('    def ${cd.methodName}(self):');
      buf.writeln('        for record in self:');
      for (final line in cd.bodyLines) {
        buf.writeln('            $line');
      }
      buf.writeln();
    }

    return buf.toString();
  }

  // ── onchange methods ──────────────────────────────────────────────────────

  static String onchangeMethods(OdooModel model) {
    if (model.onchanges.isEmpty) {
      // Auto-generate stubs for Many2one fields that requested onchange=true
      final m2oOnchange = model.fields
          .whereType<Many2one>()
          .where((f) => f.onchange)
          .toList();

      if (m2oOnchange.isEmpty) return '';

      final buf = StringBuffer();
      buf.writeln('    # ── Onchange stubs ───────────────────────────────────');
      buf.writeln();

      for (final f in m2oOnchange) {
        buf.writeln("    @api.onchange('${f.name}')");
        buf.writeln('    def _onchange_${f.name}(self):');
        buf.writeln(
            '        """Triggered when ${NamingConventions.toLabel(f.name)} changes."""');
        buf.writeln('        pass');
        buf.writeln();
      }

      return buf.toString();
    }

    final buf = StringBuffer();
    buf.writeln('    # ── Onchange methods ─────────────────────────────────');
    buf.writeln();

    for (final oc in model.onchanges) {
      final triggers = oc.triggerFields.map((t) => "'$t'").join(', ');
      buf.writeln('    @api.onchange($triggers)');
      buf.writeln('    def ${oc.methodName}(self):');
      for (final line in oc.bodyLines) {
        buf.writeln('        $line');
      }
      buf.writeln();
    }

    return buf.toString();
  }

  // ── constraint methods ────────────────────────────────────────────────────

  static String constraintMethods(OdooModel model) {
    if (model.constraints.isEmpty) return '';

    final buf = StringBuffer();
    buf.writeln(
        '    # ── Python constraints ───────────────────────────────────');
    buf.writeln();

    for (final c in model.constraints) {
      final fields = c.constrainedFields.map((f) => "'$f'").join(', ');
      buf.writeln('    @api.constrains($fields)');
      buf.writeln('    def ${c.methodName}(self):');
      buf.writeln('        for record in self:');
      if (c.bodyLines.isEmpty) {
        buf.writeln(
            "            if not record.${c.constrainedFields.first}:");
        buf.writeln(
            "                raise ValidationError("
            "'${StringUtils.escapeSingle(c.errorMessage)}')");
      } else {
        for (final line in c.bodyLines) {
          buf.writeln('            $line');
        }
      }
      buf.writeln();
    }

    return buf.toString();
  }

  // ── ORM overrides ─────────────────────────────────────────────────────────

  static String ormOverrides(OdooModel model) {
    final buf = StringBuffer();
    buf.writeln(
        '    # ── ORM overrides ────────────────────────────────────────');
    buf.writeln();

    // create
    buf.writeln('    @api.model');
    buf.writeln('    def create(self, vals):');
    if (model.createSequence) {
      buf.writeln(
          '        if not vals.get(\'sequence\'):');
      buf.writeln(
          '            vals[\'sequence\'] = self.env[\'ir.sequence\']'
          ".next_by_code('${model.modelName}') or '/'");
    }
    buf.writeln('        return super().create(vals)');
    buf.writeln();

    // write
    buf.writeln('    def write(self, vals):');
    buf.writeln('        return super().write(vals)');
    buf.writeln();

    // name_get (if rec_name != 'name')
    if (model.stringField != 'name') {
      buf.writeln('    def name_get(self):');
      buf.writeln('        result = []');
      buf.writeln('        for record in self:');
      buf.writeln(
          '            name = record.${model.stringField} or str(record.id)');
      buf.writeln('            result.append((record.id, name))');
      buf.writeln('        return result');
      buf.writeln();
    }

    return buf.toString();
  }

  // ── full render ───────────────────────────────────────────────────────────

  /// Renders the complete Python model file.
  static String render(OdooModel model) {
    return imports(model) +
        classHeader(model) +
        fieldDeclarations(model) +
        computeMethods(model) +
        onchangeMethods(model) +
        constraintMethods(model) +
        ormOverrides(model);
  }
}
