/// XML views template builder.
library odoo_model_generator.templates.view_template;

import '../core/model_builder.dart';
import '../core/field_types.dart';
import '../utils/naming_conventions.dart';

// ─────────────────────────────────────────────────────────────────────────────
//  ViewTemplate
// ─────────────────────────────────────────────────────────────────────────────

/// Builds the complete `views/<name>_view.xml` file content.
abstract final class ViewTemplate {
  ViewTemplate._();

  // ── Header / Footer ───────────────────────────────────────────────────────

  static const _xmlDecl = '<?xml version="1.0" encoding="utf-8"?>';
  static const _comment =
      '<!-- Generated by odoo_model_generator v2.0.0 -->';

  // ── Form view ─────────────────────────────────────────────────────────────

  static String _formView(OdooModel model) {
    final name = model.modelName;
    final label = NamingConventions.toLabel(name);
    final formId = NamingConventions.formViewId(name);

    // Split fields into groups: relational → second group; others → first
    final regular = model.fields
        .where((f) =>
            f is! One2many &&
            f is! Many2many &&
            f is! Text &&
            f is! Html)
        .toList();

    final notebookFields = model.fields
        .where((f) => f is Text || f is Html)
        .toList();

    final o2mFields = model.fields
        .where((f) => f is One2many || f is Many2many)
        .toList();

    // Split regular fields into two columns
    final half = (regular.length / 2).ceil();
    final left = regular.sublist(0, half);
    final right = regular.sublist(half);

    final buf = StringBuffer();

    buf.writeln('    <!-- ═══ Form View ════════════════════════════════════ -->');
    buf.writeln(
        '    <record id="$formId" model="ir.ui.view">');
    buf.writeln('        <field name="name">$label Form</field>');
    buf.writeln('        <field name="model">$name</field>');
    buf.writeln('        <field name="arch" type="xml">');
    buf.writeln('            <form string="$label">');
    buf.writeln('                <header>');
    // Status bar from first Selection field
    final selection = model.fields.whereType<Selection>().firstOrNull;
    if (selection != null) {
      buf.writeln(
          '                    <field name="${selection.name}" '
          'widget="statusbar" '
          'statusbar_visible="${selection.resolvedOptions.take(3).map((o) => o.$1).join(",")}"/>');
    }
    buf.writeln('                </header>');
    buf.writeln('                <sheet>');

    // Two-column group
    if (regular.isNotEmpty) {
      buf.writeln('                    <group>');
      if (left.isNotEmpty) {
        buf.writeln('                        <group string="General">');
        for (final f in left) {
          if (f is! Selection) {
            buf.writeln('                            ${f.toFormXML()}');
          }
        }
        buf.writeln('                        </group>');
      }
      if (right.isNotEmpty) {
        buf.writeln('                        <group string="Details">');
        for (final f in right) {
          if (f is! Selection) {
            buf.writeln('                            ${f.toFormXML()}');
          }
        }
        buf.writeln('                        </group>');
      }
      buf.writeln('                    </group>');
    }

    // Notebook for Text/Html and O2m/M2m
    final hasNotebook = notebookFields.isNotEmpty || o2mFields.isNotEmpty;
    if (hasNotebook) {
      buf.writeln('                    <notebook>');

      if (notebookFields.isNotEmpty) {
        buf.writeln('                        <page string="Notes &amp; Details">');
        for (final f in notebookFields) {
          buf.writeln('                            ${f.toFormXML()}');
        }
        buf.writeln('                        </page>');
      }

      for (final f in o2mFields) {
        final pageLabel = NamingConventions.toLabel(f.name);
        buf.writeln('                        <page string="$pageLabel">');
        buf.writeln('                            ${f.toFormXML()}');
        buf.writeln('                        </page>');
      }

      buf.writeln('                    </notebook>');
    }

    // Chatter (mail.thread)
    if (model.inherits.contains('mail.thread')) {
      buf.writeln('                    <div class="oe_chatter">');
      buf.writeln(
          '                        <field name="message_follower_ids"/>');
      buf.writeln('                        <field name="activity_ids"/>');
      buf.writeln('                        <field name="message_ids"/>');
      buf.writeln('                    </div>');
    }

    buf.writeln('                </sheet>');
    buf.writeln('            </form>');
    buf.writeln('        </field>');
    buf.writeln('    </record>');

    return buf.toString();
  }

  // ── Tree view ─────────────────────────────────────────────────────────────

  static String _treeView(OdooModel model) {
    final name = model.modelName;
    final label = NamingConventions.toLabel(name);
    final treeId = NamingConventions.treeViewId(name);

    // Show fields explicitly marked inTree=true; fall back to first 5
    var treeFields = model.fields.where((f) => f.inTree).toList();
    if (treeFields.isEmpty) {
      treeFields = model.fields
          .where((f) => f is! One2many && f is! Many2many && f is! Html)
          .take(5)
          .toList();
    }

    final buf = StringBuffer();
    buf.writeln('    <!-- ═══ Tree View ═════════════════════════════════════ -->');
    buf.writeln(
        '    <record id="$treeId" model="ir.ui.view">');
    buf.writeln('        <field name="name">$label Tree</field>');
    buf.writeln('        <field name="model">$name</field>');
    buf.writeln('        <field name="arch" type="xml">');
    buf.writeln('            <tree string="$label"');

    // Decoration hint from Selection field
    final sel = model.fields.whereType<Selection>().firstOrNull;
    if (sel != null && sel.resolvedOptions.length >= 2) {
      buf.write(
          '                decoration-success="${sel.name} == \'${sel.resolvedOptions.last.$1}\'"');
      buf.write(
          ' decoration-muted="${sel.name} == \'${sel.resolvedOptions.first.$1}\'"');
    }
    buf.writeln('>');

    for (final f in treeFields) {
      buf.writeln('                ${f.toTreeXML()}');
    }

    buf.writeln('            </tree>');
    buf.writeln('        </field>');
    buf.writeln('    </record>');

    return buf.toString();
  }

  // ── Search view ───────────────────────────────────────────────────────────

  static String _searchView(OdooModel model) {
    final name = model.modelName;
    final label = NamingConventions.toLabel(name);
    final searchId = NamingConventions.searchViewId(name);

    // Search fields
    var searchFields = model.fields.where((f) => f.inSearch).toList();
    if (searchFields.isEmpty) {
      searchFields = model.fields
          .where((f) => f is Char || f is Many2one || f is Selection)
          .take(3)
          .toList();
    }

    final buf = StringBuffer();
    buf.writeln(
        '    <!-- ═══ Search View ══════════════════════════════════════ -->');
    buf.writeln(
        '    <record id="$searchId" model="ir.ui.view">');
    buf.writeln('        <field name="name">$label Search</field>');
    buf.writeln('        <field name="model">$name</field>');
    buf.writeln('        <field name="arch" type="xml">');
    buf.writeln('            <search string="$label">');

    for (final f in searchFields) {
      buf.writeln('                ${f.toSearchXML()}');
    }

    // Filters from Selection options
    for (final sel in model.fields.whereType<Selection>()) {
      for (final opt in sel.resolvedOptions) {
        buf.writeln(
            "                <filter name=\"filter_${sel.name}_${opt.$1}\" "
            "string=\"${opt.$2}\" "
            "domain=\"[('${sel.name}', '=', '${opt.$1}')]\"/>");
      }
    }

    // Group by suggestions
    if (model.fields.any((f) => f is Many2one)) {
      buf.writeln('                <separator/>');
      buf.writeln('                <group expand="0" string="Group By">');
      for (final f in model.fields.whereType<Many2one>().take(3)) {
        buf.writeln(
            "                    <filter name=\"groupby_${f.name}\" "
            "string=\"${NamingConventions.toLabel(f.name)}\" "
            "context=\"{'group_by': '${f.name}'}\"/>");
      }
      buf.writeln('                </group>');
    }

    buf.writeln('            </search>');
    buf.writeln('        </field>');
    buf.writeln('    </record>');

    return buf.toString();
  }

  // ── Window Action ─────────────────────────────────────────────────────────

  static String _windowAction(OdooModel model) {
    final name = model.modelName;
    final label = NamingConventions.toLabel(name);
    final actionId = NamingConventions.actionId(name);

    return '''    <!-- ═══ Window Action ══════════════════════════════════════ -->
    <record id="$actionId" model="ir.actions.act_window">
        <field name="name">$label</field>
        <field name="res_model">$name</field>
        <field name="view_mode">tree,form</field>
        <field name="context">{}</field>
        <field name="help" type="html">
            <p class="o_view_nocontent_smiling_face">
                No records found. Create your first one!
            </p>
        </field>
    </record>
''';
  }

  // ── Menu item ─────────────────────────────────────────────────────────────

  static String _menuItem(OdooModel model) {
    final name = model.modelName;
    final label = NamingConventions.toLabel(name);
    final menuId = NamingConventions.menuId(name);
    final actionId = NamingConventions.actionId(name);

    return '''    <!-- ═══ Menu Item ══════════════════════════════════════════ -->
    <menuitem
        id="$menuId"
        name="$label"
        action="$actionId"
        parent="base.menu_administration"
        sequence="100"/>
''';
  }

  // ── Full render ───────────────────────────────────────────────────────────

  /// Renders the complete views XML file.
  static String render(OdooModel model) {
    final buf = StringBuffer();
    buf.writeln(_xmlDecl);
    buf.writeln(_comment);
    buf.writeln('<odoo>');
    buf.writeln();
    buf.write(_formView(model));
    buf.writeln();
    buf.write(_treeView(model));
    buf.writeln();
    buf.write(_searchView(model));
    buf.writeln();
    buf.write(_windowAction(model));
    buf.writeln();
    buf.write(_menuItem(model));
    buf.writeln('</odoo>');
    return buf.toString();
  }
}
